### PR TITLE
Binary search added

### PR DESCRIPTION
**Pull request by thetaniyagupta**

### CODE REVIEW

**Comment by thetaniyagupta** [comment]
> _No description provided._

@Bhupesh-V Got a conflict. Can you help in resolving it.

**Comment by Bhupesh-V** [comment]
Hey @thetaniyagupta did you update you fork before pushing any changes
I changed some thing on master

**Comment by thetaniyagupta** [comment]
> Hey @thetaniyagupta did you update you fork before pushing any changes
> I changed some thing on master

 @Bhupesh-V , i pushed changes without updating. But then after i saw conflict, I updated the fork, but i couldn't resolve the issue. Need help on it

**Comment by Bhupesh-V** [comment]
Yeah that happens 
Try This

```
git checkout master
git pull
git checkout <branch>
git add [files that were conflicted]
git commit
git push
```

**Comment by thetaniyagupta** [comment]
> Yeah that happens
> Try This
> 
> ```
> git checkout master
> git pull
> git checkout <branch>
> git add [files that were conflicted]
> git commit
> git push
> ```

@Bhupesh-V  resolved the conflict

**Comment by Bhupesh-V** [comment]
Yeah :100: 
:sunglasses: 
Also share this repo with others who want to contribute to Open Source.

**Pull request merged**
